# Environment Configuration
browser=chrome
implicitWait=10
headless=false


# Application URLs (UPDATED - SAME DOMAIN FOR BOTH)
adminPortalURL=https://stg.rrr.dashboard.foxberry.live/
citizenPortalURL=https://stg.rrr.dashboard.foxberry.live/


# Role Credentials

# Admin Credentials
adminUsername=8007922341
adminPassword=123


# Citizen (Contractor) Credentials
citizenUsername=9767945710
citizenPassword=123


# Framework Paths
testDataPath=src/test/resources/testdata/
screenshotPath=src/test/resources/screenshots/
reportPath=target/reports/