name: Selenium CI Pipeline

on:
  push:
    branches:
      - test-branch
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:   # 👈 enables manual run

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
      
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Run Tests
        run: mvn clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: target/surefire-reports/
